[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

# 1. Laravel Server
[program:laravel-serve]
command=php artisan serve --host=0.0.0.0 --port=8000
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/laravel-serve.err.log
stdout_logfile=/var/log/supervisor/laravel-serve.out.log

# 2. Worker (З вашими налаштуваннями черг!)
[program:laravel-worker]
command=php artisan queue:work --queue=high,default --tries=3 --timeout=90
autostart=true
autorestart=true
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/supervisor/worker.log

# 3. Scheduler
[program:laravel-scheduler]
command=php artisan schedule:work
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/scheduler.err.log
stdout_logfile=/var/log/supervisor/scheduler.out.log
